### ISSUE TITLE
nice custom URL for project pages

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#292]
- Display project URL as : ouishare.net/project-name (ouishare.net/gouvernances)

- Use Title field for slug

**Comment by karnaud** [comment]
http://ouishare.pitchme.webfactional.com/en/projects/ouishare-labs ?

**Comment by kirilind** [comment]
In regard to
> On the technical side it will be tough to find a way to have multiple types of entities (communities, projects) on the root path (ouishare.net/xxx) as all the routing system would need to be adapted. 

shall we keep project slugs as they are, or add redirects to them as well?
See also #242

**Comment by kirilind** [comment]
i would agree with Fran that the best would be to offer a way to access projects via  ouishare.net/projectname, even if it's a redirect. But should we make them somehow manageable in the backend (community page edit, for example) so that people would be aware of this option?

Also how will it work for new projects, will they gain the slug automatically or will a redirect creation process need to be run every now and then?

**Comment by karnaud** [comment]
We add this kind of url for community page.
ex : http://ouishare.pitchme.webfactional.com/paris

For me the problem is, What shall we do if there is a project call paris also ? Do we redirect through the community or the project ?

Otherwise the code in the route is quite simple : 

```get '/:id', to: 'communities#show', constraints: lambda { |request| Community.find_by(slug: request.path_parameters[:id]) }```

it means, for example xxx/paris, if there is a community calls paris we redirect to this page otherwise we continue...

**Comment by pitch-me-git** [comment]
try with  /projects/projectname

**Comment by karnaud** [comment]
This url is already working : 
ex : http://ouishare.pitchme.webfactional.com/projects/ouishare-labs
